// Generated by CoffeeScript 1.10.0
module.exports = function(app, wagner) {
  var Consumer, Producer;
  Producer = wagner.get('Producer');
  Consumer = wagner.get('Consumer');
  app.post('/queue/store', function(req, res, next) {
    return Producer.addMessage(req.body, function(err, response) {
      if (!err) {
        return res.status(200).json(response);
      } else {
        return res.status(500).json(err);
      }
    });
  });
  return app.get('/queue/process', function(req, res, next) {
    return Consumer.getMessages(function(err, response) {
      if (!err) {
        return res.status(200).json(response);
      } else {
        return res.status(500).json(err);
      }
    });
  });
};
