// Generated by CoffeeScript 1.10.0
var Consumer, Producer, Queue;

Producer = require('./Producer');

Queue = require('./Queue');

Consumer = require('./Consumer');

module.exports = function(sequelize, wagner) {
  wagner.factory('Producer', function() {
    return new Producer(sequelize, wagner);
  });
  wagner.factory('Queue', function() {
    return new Queue(sequelize, wagner);
  });
  return wagner.factory('Consumer', function() {
    return new Consumer(sequelize, wagner);
  });
};
