// Generated by CoffeeScript 1.10.0
var _, modelName;

_ = require('underscore');

modelName = 'message';


/*Model for the table message */

module.exports = function(sequelize, DataTypes) {
  var Message;
  return Message = sequelize.define(modelName, {
    id: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      primaryKey: true,
      allowNull: false
    },
    message_id: {
      type: DataTypes.STRING(100)
    },
    body: {
      type: DataTypes.STRING(300)
    },
    processed: {
      type: DataTypes.BOOLEAN,
      defaultValue: 0
    }
  }, {
    getterMethods: {
      getLockedStatus: function() {
        if (_.isBoolean(this.lock)) {
          return this.setDataValue('lock', false);
        }
      }
    },
    setterMethods: {
      setLock: function(value) {
        return this.setDataValue('lock', value);
      }
    },
    tableName: modelName,
    createdAt: "created_at",
    updatedAt: "updated_at",
    deletedAt: "deleted_at",
    timestamps: true,
    paranoid: true,
    indexes: [
      {
        name: 'idx_message_id',
        fields: ['message_id']
      }
    ]
  });
};
